---
driver:
  name: vagrant

verifier:
  name: inspec

provisioner:
  # client_rb:
    # treat_deprecation_warnings_as_errors: true
    # resource_cloning: false
  name: chef_zero
  log_file: "/kitchen-chef-client.log"
  # log_level: debug
  attributes:
    apt:
      confd:
        install_recommends: false

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.8
    run_list:
    - recipe[yum]
  - name: centos-7.2
    run_list:
    - recipe[yum]
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2
      guest: windows
      communicator: winrm
      gui: false
      platform: windows

suites:
  - name: chef12
    driver:
      require_chef_omnibus: 12.22.5
    verifier:
      inspec_tests:
        - test/smoke/v6
    excludes:
      - windows-2012R2
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef13
    driver:
      require_chef_omnibus: 13.9.4
    verifier:
      inspec_tests:
        - test/smoke/v6
    excludes:
      - windows-2012R2
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef14
    driver:
      require_chef_omnibus: 14.2.0
    verifier:
      inspec_tests:
        - test/smoke/v6
    excludes:
      - windows-2012R2
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef13win
    driver:
      require_chef_omnibus: 13.9.4
    verifier:
      inspec_tests:
        - test/smoke/v6windows
    run_list:
      - recipe[filebeat_test::defaultv6]
    includes:
      - windows-2012R2

  - name: chef13runit
    driver:
      require_chef_omnibus: 13.9.4
    excludes:
      - windows-2012R2
    run_list:
      - recipe[filebeat::default]

  - name: chef13preview
    driver:
      chef_version: 13.9.4
    verifier:
      inspec_tests:
        - test/smoke/v6
    excludes:
      - windows-2012R2
    run_list:
      - recipe[filebeat_test::defaultv6preview]
    attributes:
      filebeat:
        version: 6.0.0-beta2
