---
driver:
  name: dokken
  privileged: true

transport:
  name: dokken

verifier:
  name: inspec

provisioner:
  name: dokken
  attributes:
    apt:
      confd:
        install_recommends: false

platforms:
  - name: ubuntu14
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: ubuntu16
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian8
    driver:
      image: debian:8.9
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: debian9
    driver:
      image: dokken/debian-9
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -qq
        - RUN /usr/bin/apt-get install -y net-tools apt-transport-https initscripts procps lsb-release curl gnupg

  - name: centos6
    driver:
      image: centos:6.9
      pid_one_command: /sbin/init
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which curl

  - name: centos7
    driver:
      image: centos:7
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: fedora26
    driver:
      image: fedora:26
      pid_one_command: /usr/lib/systemd/systemd
      platform: rhel
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts systemd-sysv which lsof curl

  - name: amazon
    driver:
      image: amazonlinux:2017.03
      pid_one_command: /sbin/init
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts which

  - name: amazon2
    driver:
      image: amazonlinux:2
      pid_one_command: /usr/lib/systemd/systemd
      platform: amazon
      intermediate_instructions:
        - RUN yum install -y net-tools initscripts

suites:
  - name: chef12
    driver:
      chef_version: 12.22.5
    verifier:
      inspec_tests:
        - test/smoke/v6
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef13
    driver:
      chef_version: 13.9.4
    verifier:
      inspec_tests:
        - test/smoke/v6
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef14
    driver:
      chef_version: 14.2.0
    verifier:
      inspec_tests:
        - test/smoke/v6
    run_list:
      - recipe[filebeat_test::defaultv6]

  - name: chef13runit
    driver:
      chef_version: 13.9.4
    verifier:
      inspec_tests:
        - test/smoke/v6runit
    run_list:
      - recipe[filebeat_test::defaultv6runit]

  - name: chef13-preview
    driver:
      chef_version: 13.9.4
    run_list:
      - recipe[filebeat_test::defaultv6preview]
