default["gearman"]["version"] = "1.0.2*"
default["gearman"]["ip"] = "192.168.102.101"
default['gearman']['mysql']['host'] = "jb-db-master.cbuof78eddep.us-east-1.rds.amazonaws.com"
default['gearman']['mysql']['user'] = "gearman"
default['gearman']['mysql']['password'] = "jbgearman"
default['gearman']['mysql']['db'] = "gearman"
default['gearman']['mysql']['table'] = "gearman_queue"
default['gearman']['mysql']['port'] = "3306"
