name             'zend'
maintainer       'Ian Elliott'
maintainer_email 'ian@jumbleberry.com'
license          'All rights reserved'
description      'Installs/Configures ZF1'
long_description 'Installs/Configures ZF1 for JB applications'
version          '0.0.1'