<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.0.10deb1 setup script
 * Date: Wed, 04 May 2016 17:43:51 +0000
 */

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['LoginCookieValidity'] = 756000;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
?>