#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=6379
EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis.pid
CONF="/etc/redis/redis.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis server..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)

            echo "Stopping Redis server..."
            $CLIEXEC -p $REDISPORT shutdown
            
            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis server to shutdown ..."
                sleep 1
            done
            
            echo "Redis server stopped"
        fi
        ;;
    status)
        if [ -f $PIDFILE ]; then
            echo "Redis server is running"
        else
            echo "Redis server is not running"
        fi
        ;;
    restart)
        if [ ! -f $PIDFILE ]; then
            echo "Starting Redis server..."
            $EXEC $CONF
        else
            PID=$(cat $PIDFILE)

            echo "Stopping Redis server..."
            $CLIEXEC -p $REDISPORT shutdown

            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis server to shutdown ..."
                sleep 1
            done
            
            echo "Redis server stopped"

            echo "Starting Redis server..."
            $EXEC $CONF
        fi
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
