#!/bin/sh
#
# Simple Redis init.d script conceived to work on Linux systems
# as it does use of the /proc filesystem.

REDISPORT=26379
EXEC=/usr/local/bin/redis-sentinel
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/sentinel.pid
CONF="/etc/redis/sentinel.conf"

case "$1" in
    start)
        if [ -f $PIDFILE ]
        then
            echo "$PIDFILE exists, process is already running or crashed"
        else
            echo "Starting Redis Sentinel..."
            $EXEC $CONF
        fi
        ;;
    stop)
        if [ ! -f $PIDFILE ]
        then
            echo "$PIDFILE does not exist, process is not running"
        else
            PID=$(cat $PIDFILE)

            echo "Stopping Redis Sentinel..."
            $CLIEXEC -p $REDISPORT shutdown

            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis Sentinel to shutdown ..."
                sleep 1
            done
            
            echo "Redis Sentinel stopping"
        fi
        ;;
    status)
        if [ -f $PIDFILE ]; then
            echo "Redis Sentinel is running"
        else
            echo "Redis Sentinel is not running"
        fi
        ;;
    restart)
        if [ ! -f $PIDFILE ]; then
            echo "Starting Redis Sentinel..."
            $EXEC $CONF
        else
            PID=$(cat $PIDFILE)

            echo "Stopping Redis Sentinel..."
            $CLIEXEC -p $REDISPORT shutdown

            while [ -x /proc/${PID} ]
            do
                echo "Waiting for Redis Sentinel to shutdown ..."
                sleep 1
            done
            
            echo "Redis Sentinel stopped"

            echo "Starting Redis Sentinel..."
            $EXEC $CONF
        fi
        ;;
    *)
        echo "Please use start, stop, restart or status as first argument"
        ;;
esac
